using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace OmniRelay.Dispatcher.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class DispatcherGenerator : IIncrementalGenerator
{
    private const string AttributeName = "OmniRelay.Dispatcher.CodeGen.DispatcherDefinitionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
#pragma warning disable IDE0200 // Lambda expression can be removed (style); keep for clarity.
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider<ClassDeclarationSyntax?>(IsCandidate, GetSemanticTarget)
            .Where(static model => model is not null)!;
#pragma warning restore IDE0200

        var compilationAndClasses = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, pair) =>
        {
            var (compilation, classes) = pair;
            foreach (var cls in classes)
            {
                if (cls is null)
                {
                    continue;
                }

                if (compilation.GetTypeByMetadataName(AttributeName) is null)
                {
                    // Attribute not referenced; skip with a diagnostic message.
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            id: "ORGEN001",
                            title: "DispatcherDefinitionAttribute missing",
                            messageFormat: "DispatcherDefinitionAttribute was not found in compilation; dispatcher generation skipped.",
                            category: "Usage",
                            DiagnosticSeverity.Warning,
                            isEnabledByDefault: true),
                        Location.None));
                    return;
                }

                GenerateDispatcher(spc, cls);
            }
        });
    }

    private static bool IsCandidate(SyntaxNode node, CancellationToken _) =>
        node is ClassDeclarationSyntax { AttributeLists.Count: > 0, Modifiers: var mods }
        && mods.Any(static m => m.IsKind(SyntaxKind.PartialKeyword));

    private static ClassDeclarationSyntax? GetSemanticTarget(GeneratorSyntaxContext context, CancellationToken _)
    {
        if (context.Node is not ClassDeclarationSyntax classDecl)
        {
            return null;
        }

        foreach (var list in classDecl.AttributeLists)
        {
            foreach (var attribute in list.Attributes)
            {
                var symbol = context.SemanticModel.GetSymbolInfo(attribute, _).Symbol as IMethodSymbol;
                if (symbol?.ContainingType.ToDisplayString() == AttributeName)
                {
                    return classDecl;
                }
            }
        }

        return null;
    }

    private static void GenerateDispatcher(SourceProductionContext context, ClassDeclarationSyntax cls)
    {
        var ns = GetNamespace(cls);
        var className = cls.Identifier.Text;

        // Derive service name from attribute argument; default to class name if missing.
        var serviceName = "";
        var attr = cls.AttributeLists
            .SelectMany(static l => l.Attributes)
            .First(a => IsDispatcherAttribute(a));

        foreach (var arg in attr.ArgumentList?.Arguments ?? default)
        {
            if (arg.Expression is LiteralExpressionSyntax literal && literal.IsKind(SyntaxKind.StringLiteralExpression))
            {
                serviceName = literal.Token.ValueText;
                break;
            }
        }

        if (string.IsNullOrWhiteSpace(serviceName))
        {
            serviceName = className;
        }

        var source = $$"""
// <auto-generated/>
using System;
using OmniRelay.Dispatcher;

namespace {{ns}}
{
    partial class {{className}}
    {
        public static Dispatcher CreateDispatcher(IServiceProvider services)
        {
            var options = new DispatcherOptions("{{serviceName}}");
            Configure(services, options);
            return new Dispatcher(options);
        }

        static partial void Configure(IServiceProvider services, DispatcherOptions options);
    }
}
""";

        context.AddSource($"{className}.Dispatcher.g.cs", source);
    }

    private static string GetNamespace(ClassDeclarationSyntax cls)
    {
        var current = cls.Parent;
        while (current is not null)
        {
            if (current is NamespaceDeclarationSyntax ns)
            {
                return ns.Name.ToString();
            }

            if (current is FileScopedNamespaceDeclarationSyntax fileNs)
            {
                return fileNs.Name.ToString();
            }

            current = current.Parent;
        }

        return "Global";
    }

    private static bool IsDispatcherAttribute(AttributeSyntax attributeSyntax)
    {
        var name = attributeSyntax.Name.ToString();
        return name.EndsWith("DispatcherDefinition", StringComparison.Ordinal) ||
               name.EndsWith("DispatcherDefinitionAttribute", StringComparison.Ordinal) ||
               name.Equals("DispatcherDefinition", StringComparison.Ordinal) ||
               name.Equals("DispatcherDefinitionAttribute", StringComparison.Ordinal);
    }
}
