using System.Text;
using Google.Protobuf.Reflection;

namespace OmniRelay.Codegen.Protobuf.Core;

/// <summary>
/// Emits a CLI-specific registration partial that connects generated message serializers
/// to the OmniRelay.Cli.Core ProtobufPayloadRegistry (AOT-friendly, no reflection).
/// </summary>
public static class ProtobufCliRegistrationEmitter
{
    public sealed record EmittedRegistration(string HintName, string Source);

    public static EmittedRegistration Emit(FileDescriptorSet descriptorSet, string descriptorPath)
    {
        var ns = "OmniRelay.Cli.Core";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("public static partial class ProtobufPayloadRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    static partial void RegisterAll(ProtobufPayloadRegistry registry)");
        sb.AppendLine("    {");
        foreach (var file in descriptorSet.File)
        {
            foreach (var message in file.MessageType)
            {
                var fullName = QualifiedName(file.Package, message.Name);
                sb.AppendLine($"        registry.Register(\"{fullName}\", static json => {fullName}OmniRelaySerializer.Serialize(json));");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var hint = CreateHint(descriptorPath);
        return new EmittedRegistration(hint, sb.ToString());
    }

    private static string QualifiedName(string package, string name)
    {
        if (string.IsNullOrWhiteSpace(package))
        {
            return name;
        }

        return string.Concat(package, '.', name);
    }

    private static string CreateHint(string descriptorPath)
    {
        var descriptorName = Path.GetFileNameWithoutExtension(descriptorPath);
        return $"{descriptorName}_ProtobufCliRegistration.g.cs";
    }
}
